
cc_library(
    name = "window",
    srcs = ["window/window.cc"],
    hdrs = ["window/window.h"],
    deps = [
      "//third_party/glfw",
      "//third_party/glm",
      "@rules_vulkan//vulkan:vulkan_cc_library"
    ],
    visibility = ["//graphics/src:__subpackages__"],
)